"""add password column

Revision ID: 99585b5df75d
Revises: 97653eac33a6
Create Date: 2026-07-27 15:56:20.719357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99585b5df75d'
down_revision = '97653eac33a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
