"""rename email column

Revision ID: f5106a4e226d
Revises: eefe42fdedb1
Create Date: 2026-07-17 10:45:36.950629

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5106a4e226d"
down_revision = "eefe42fdedb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("email", new_column_name="email_address")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("email_address", new_column_name="email")
    # ### end Alembic commands ###
