"""add profile table

Revision ID: faf18f59ebed
Revises: f5106a4e226d
Create Date: 2026-07-21 09:58:24.079179

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "faf18f59ebed"
down_revision = "f5106a4e226d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column(
            "gender", sa.Enum("male", "female", name="gender_enums"), nullable=False
        ),
        sa.Column(
            "role", sa.Enum("admin", "staff", "user", name="roles_enum"), nullable=False
        ),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profile_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
        sa.UniqueConstraint("user_id", name=op.f("uq_profile_user_id")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_email"), type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_users_email_address"), ["email_address"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_email_address"), type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_users_email"), ["email_address"]
        )

    op.drop_table("profile")
    # ### end Alembic commands ###
